PUT http://localhost:8080/api/account/222
Content-Type: application/json

{
  "firstName": "Mary",
  "lastName": "Dillard",
  "email": "Mdauls2022@Gmail.com",
  "username": "Daul2022",
  "password": "password123",
  "rank": 3,
  "orderId":1
}