
POST http://localhost:8080/api/cart
Content-Type: application/json

{
  "productId": 28,
  "productName": "Root Beer Jelly Beans",
  "price": 6.89,
  "quantity": 5,
  "account": {
    "id": 1
  }
}



