
POST http://localhost:8080/api/cart
Content-Type: application/json

{
  "orderId": 123,
  "productId": 43,
  "productName": "Sour Jelly Beans",
  "price": 6.89,
  "quantity": 5,
  "account": {
    "firstName": "Mary",
    "lastName": "Dauls",
    "email": "Mdauls2022@Gmail.com",
    "username": "Dauls2022",
    "password": "password123",
    "rank": 2,
    "id": 1
  }
}



